# Generated by Django 5.0.4 on 2024-04-22 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartyModel",
            fields=[
                (
                    "party_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("party_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="EntryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chalan_number", models.CharField(max_length=50)),
                ("bill_number", models.CharField(max_length=50)),
                ("rate", models.IntegerField()),
                ("tax", models.IntegerField(default=0, null=True)),
                ("gst", models.IntegerField()),
                ("total", models.IntegerField()),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.partymodel"
                    ),
                ),
            ],
        ),
    ]
